apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache-system
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: ubuntu/apache2
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-system
spec:
  selector:
    app: apache
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
