apiVersion: v1
kind: Secret
metadata:
    name: github
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:lccaZIZVPw==,iv:IzW5mLKjeUPK1Zh6IhPxNOHvLl64gy70yCK2KNSD0Jw=,tag:EsZP6CGKq0Vp2deDxZ9oHg==,type:str]
    password: ENC[AES256_GCM,data:QshncNGY2YDDbLFBPuhAjTkWUEfRPw0+CtLWxNh1PiXifMNz8F1GYg==,iv:EkhnfYQQB6Wx8ZrZBAgDAsWeOp0WEcnpMeYoxJNpwd4=,tag:8uU+GHJ5k2BW9klHH+TJEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-05T05:46:22Z"
    mac: ENC[AES256_GCM,data:CcU6HWndsiaSZNTTxK6y64/qa47RveyQmjq4RkjEtMxJRjKUvnvFdXzeYHZTDdGa20PrtRlS/U4IukZLu1ljFn+DJE/h5RhIxRo/myZq1FAogXEEQ/FDsO+AYVrK1/RdKf41D5j+R3Rxeu9WiZbE7RDQxQPelLc49cDtFkJbkRA=,iv:x6HAlnEY9qBhotBOxV6wT/Y1Ixf3bQvdIyWmJ0VveK0=,tag:DMWdBMIzckBEOJ1MTvcCew==,type:str]
    pgp:
        - created_at: "2024-11-05T05:46:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7cxbW+q6X7VAQ//ckhELncU1xBXHLhK9akmMRrpZwtSZJwYNQ1DUqPQwSQi
            PseN5HdWt9oxUeGU7O1kjN3wmyKAcZyxTdOLoAXAe7kKhhJvNNXavyBUR6qeNigF
            gMgVTUEZad5Z/RjpHsADifjNzbe6TtLCWroqfyHUAfaumnXTe7dotXiY+1agOngu
            mLdllPVCtc1A4msWvUZ79toAbhgKaP5qjUvJpvyMlUFhYFWpAuGfMl7lZRmFMI6v
            kULXEEvF0JKlEEoe4d9bZw1Gkd3N1QAtedJD5+6j+z0yqKPNXwSjzkIvWSlzbbKB
            TOrff47vROEZt3ktM2XWNl+SMEz2pkYP3O9k8+BnFUekoWMt3UvjRtEnegCw6XXf
            M2CeRC+g3yluabdShpE0c/xp3DokKLHMMR4yI9QzETTPJU7hsw1O005U6DE/Tjj2
            HHg3zJ8+sbLyzHwgL6GtwfDHQ094IwUG5JOnIgjkY4U+h3Np6m/C3z9A4RgC9fKp
            JeYasDO7UkmaAed7wKA/MQK0mAoRnEsKJRN+ll7lkrSOvFskV3FKhSovzKc6oBTf
            XjL+/wt7/wm5MorwXgPVcGcBpG5BaIazPuseB05ipbXi1xnH0UdEt2eZEP/ZokvM
            Bj58gF7ck18rIRinT5FdebOOnPUct9SnudTsyqtRL8pOxkmNZNf1GJjHSpPTr9nS
            XgFsPU9vioeDIdAYs2urp3s14DIv/5G3l3flFDFebDuDM0GYu6/51pEyeKJFYR4f
            CL/Z6G2gZ0PKOfwLZJ90vK8WDqMww6mKi/YNNICWhLsodsBYgZZ/132cM+KGlA4=
            =vydR
            -----END PGP MESSAGE-----
          fp: 7C1C8D4CACEE1A81C196E0798D01222BD13CEAC3
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
